// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5276/' | (string & {});
};

export type AssignPermissionRequest = {
    roleId: string;
    permissionResource: string;
    permissionAction: string;
};

export type AssignRoleRequest = {
    role: string;
};

export type AuthenticationResponse = {
    token: string;
    refreshToken: string;
    tenantId: string;
    user: UserResponse;
};

export type CreateTenantRequest = {
    name: string;
    subdomain: string;
};

export type DeactivateTenantRequest = {
    tenantId: string;
};

export type Filter = {
    field?: string;
    operator?: Operator;
    value?: unknown;
};

export type GenerateInviteRequest = {
    tenantId: string;
    expiresIn: string;
    maxUses?: number | string;
};

export const InviteStatus = {
    ACTIVE: 'Active',
    EXHAUSTED: 'Exhausted',
    REVOKED: 'Revoked'
} as const;

export type InviteStatus = typeof InviteStatus[keyof typeof InviteStatus];

export type LoginByTelegramRequest = {
    initData: string;
};

export type Operator = number;

export type PagedRequest = {
    page?: number | string;
    pageSize?: number | string;
    filters?: null | Array<Filter>;
    sorts?: null | Array<Sort>;
};

export type PagedResponseOfTenantLinkResponse = {
    items?: Array<TenantLinkResponse>;
    page?: number | string;
    pageSize?: number | string;
    totalCount?: number | string;
    hasNextPage?: boolean;
};

export type PagedResponseOfTenantResponse = {
    items?: Array<TenantResponse>;
    page?: number | string;
    pageSize?: number | string;
    totalCount?: number | string;
    hasNextPage?: boolean;
};

export type PagedResponseOfUserPagedResponse = {
    items?: Array<UserPagedResponse>;
    page?: number | string;
    pageSize?: number | string;
    totalCount?: number | string;
    hasNextPage?: boolean;
};

export type PermissionResponse = {
    id: string;
    resource: string;
    action: string;
    fullPermission: string;
};

export type RefreshTokenRequest = {
    refreshToken: string;
};

export type RevokePermissionRequest = {
    roleId: string;
    permissionId: string;
};

export type RoleBriefResponse = {
    id: string;
    name: string;
    displayName: string;
};

export type RoleRequest = {
    name: string;
    displayName: string;
    description: null | string;
};

export type RoleResponse = {
    id: string;
    name: string;
    displayName: string;
    description: null | string;
    isActive: boolean;
    createdAt: string;
    permissions: Array<PermissionResponse>;
};

export type RoleUpdateRequest = {
    name: string;
    displayName: string;
    description: null | string;
};

export type Sort = {
    field?: string;
    isDescending?: boolean;
};

export type TelegramUserDataResponse = {
    id: number | string;
    username: null | string;
    firstName: string;
    lastName: null | string;
    languageCode: null | string;
    photoUrl: null | string;
    isPremium: null | boolean;
};

export type TenantGeneralResponse = {
    tenantId: string;
    tenantName: string;
    tenantSubDomain: string;
    tenantStatus: TenantStatus;
    users: Array<TenantUserResponse>;
};

export type TenantLinkResponse = {
    tenantLinkId: string;
    inviteLink: string;
    coutOfUsage: number | string;
    maxUses: number | string;
    expiresIn: string;
    status: InviteStatus;
};

export type TenantResponse = {
    id: string;
    name: string;
    subdomain: string;
    status: TenantStatus;
};

export const TenantStatus = { ACTIVE: 'Active', INACTIVE: 'Inactive' } as const;

export type TenantStatus = typeof TenantStatus[keyof typeof TenantStatus];

export type TenantUserResponse = {
    userId: string;
    firstName: string;
    userName: string;
    telegramId: number | string;
    roles: Array<RoleBriefResponse>;
};

export type UpdateUserRequest = {
    firstName: string;
    lastName: null | string;
};

export type UserPagedResponse = {
    id: string;
    firstName: string;
    lastName: null | string;
    createdAt: string;
    isActive: boolean;
    telegramData: null | TelegramUserDataResponse;
};

export type UserResponse = {
    id: string;
    firstName: string;
    lastName: null | string;
    telegramData: null | TelegramUserDataResponse;
    phoneNumber: null | string;
    createdAt: string;
    isActive: boolean;
    lastLogin: null | string;
    roles: Array<RoleBriefResponse>;
    permissions: Array<PermissionResponse>;
};

export type GetApiUsersByUserIdRolesData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/Users/{userId}/roles';
};

export type GetApiUsersByUserIdRolesResponses = {
    /**
     * OK
     */
    200: Array<RoleResponse>;
};

export type GetApiUsersByUserIdRolesResponse = GetApiUsersByUserIdRolesResponses[keyof GetApiUsersByUserIdRolesResponses];

export type PostApiUsersByUserIdRolesData = {
    body: AssignRoleRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/Users/{userId}/roles';
};

export type PostApiUsersByUserIdRolesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiUsersByUserIdRolesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiUsersByUserIdRolesResponse = PostApiUsersByUserIdRolesResponses[keyof PostApiUsersByUserIdRolesResponses];

export type DeleteApiUsersByUserIdRolesByRoleData = {
    body?: never;
    path: {
        userId: string;
        role: string;
    };
    query?: never;
    url: '/api/Users/{userId}/roles/{role}';
};

export type DeleteApiUsersByUserIdRolesByRoleErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiUsersByUserIdRolesByRoleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUsersByUserIdRolesByRoleResponse = DeleteApiUsersByUserIdRolesByRoleResponses[keyof DeleteApiUsersByUserIdRolesByRoleResponses];

export type GetApiUsersByUserIdPermissionsData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/Users/{userId}/permissions';
};

export type GetApiUsersByUserIdPermissionsResponses = {
    /**
     * OK
     */
    200: Array<PermissionResponse>;
};

export type GetApiUsersByUserIdPermissionsResponse = GetApiUsersByUserIdPermissionsResponses[keyof GetApiUsersByUserIdPermissionsResponses];

export type GetApiUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users/Me';
};

export type GetApiUsersMeResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetApiUsersMeResponse = GetApiUsersMeResponses[keyof GetApiUsersMeResponses];

export type DeleteApiUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type DeleteApiUsersByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiUsersByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUsersByIdResponse = DeleteApiUsersByIdResponses[keyof DeleteApiUsersByIdResponses];

export type GetApiUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type GetApiUsersByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiUsersByIdResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetApiUsersByIdResponse = GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PutApiUsersByIdData = {
    body: UpdateUserRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type PutApiUsersByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutApiUsersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiUsersGetAllData = {
    body: PagedRequest;
    path?: never;
    query?: never;
    url: '/api/Users/GetAll';
};

export type PostApiUsersGetAllResponses = {
    /**
     * OK
     */
    200: PagedResponseOfUserPagedResponse;
};

export type PostApiUsersGetAllResponse = PostApiUsersGetAllResponses[keyof PostApiUsersGetAllResponses];

export type GetApiTenantsByTenantIdData = {
    body?: never;
    path?: never;
    query: {
        tenantId: string;
    };
    url: '/api/Tenants/{tenantId}';
};

export type GetApiTenantsByTenantIdErrors = {
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetApiTenantsByTenantIdResponses = {
    /**
     * OK
     */
    200: TenantGeneralResponse;
};

export type GetApiTenantsByTenantIdResponse = GetApiTenantsByTenantIdResponses[keyof GetApiTenantsByTenantIdResponses];

export type PostApiTenantsData = {
    body: CreateTenantRequest;
    path?: never;
    query?: never;
    url: '/api/Tenants';
};

export type PostApiTenantsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PostApiTenantsResponses = {
    /**
     * OK
     */
    200: TenantResponse;
};

export type PostApiTenantsResponse = PostApiTenantsResponses[keyof PostApiTenantsResponses];

export type PostApiTenantsGetAllData = {
    body: PagedRequest;
    path?: never;
    query?: never;
    url: '/api/Tenants/GetAll';
};

export type PostApiTenantsGetAllErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiTenantsGetAllResponses = {
    /**
     * OK
     */
    200: PagedResponseOfTenantResponse;
};

export type PostApiTenantsGetAllResponse = PostApiTenantsGetAllResponses[keyof PostApiTenantsGetAllResponses];

export type DeactivateTenantData = {
    body: DeactivateTenantRequest;
    path?: never;
    query?: never;
    url: '/api/Tenants/Deactivate';
};

export type DeactivateTenantErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeactivateTenantResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeactivateTenantResponse = DeactivateTenantResponses[keyof DeactivateTenantResponses];

export type GenerateInviteLinkData = {
    body: GenerateInviteRequest;
    path?: never;
    query?: never;
    url: '/api/Tenants/GenerateInviteLink';
};

export type GenerateInviteLinkErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GenerateInviteLinkResponses = {
    /**
     * OK
     */
    200: string;
};

export type GenerateInviteLinkResponse = GenerateInviteLinkResponses[keyof GenerateInviteLinkResponses];

export type PostApiTenantsGetTenantInviteLinksByTenantIdData = {
    body: PagedRequest;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/Tenants/GetTenantInviteLinks/{tenantId}';
};

export type PostApiTenantsGetTenantInviteLinksByTenantIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiTenantsGetTenantInviteLinksByTenantIdResponses = {
    /**
     * OK
     */
    200: PagedResponseOfTenantLinkResponse;
};

export type PostApiTenantsGetTenantInviteLinksByTenantIdResponse = PostApiTenantsGetTenantInviteLinksByTenantIdResponses[keyof PostApiTenantsGetTenantInviteLinksByTenantIdResponses];

export type PostApiTenantsRevokeTenantInviteByTokenData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/api/Tenants/RevokeTenantInvite/{token}';
};

export type PostApiTenantsRevokeTenantInviteByTokenErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiTenantsRevokeTenantInviteByTokenResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiTenantsRevokeTenantInviteByTokenResponse = PostApiTenantsRevokeTenantInviteByTokenResponses[keyof PostApiTenantsRevokeTenantInviteByTokenResponses];

export type GetApiRolesGetAllByTenantIdData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/Roles/GetAll/{tenantId}';
};

export type GetApiRolesGetAllByTenantIdResponses = {
    /**
     * OK
     */
    200: Array<RoleResponse>;
};

export type GetApiRolesGetAllByTenantIdResponse = GetApiRolesGetAllByTenantIdResponses[keyof GetApiRolesGetAllByTenantIdResponses];

export type GetApiRolesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Roles/{id}';
};

export type GetApiRolesByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiRolesByIdResponses = {
    /**
     * OK
     */
    200: RoleResponse;
};

export type GetApiRolesByIdResponse = GetApiRolesByIdResponses[keyof GetApiRolesByIdResponses];

export type PutApiRolesByIdData = {
    body: RoleUpdateRequest;
    path?: never;
    query: {
        id: string;
    };
    url: '/api/Roles/{id}';
};

export type PutApiRolesByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type PutApiRolesByIdResponses = {
    /**
     * OK
     */
    200: RoleResponse;
};

export type PutApiRolesByIdResponse = PutApiRolesByIdResponses[keyof PutApiRolesByIdResponses];

export type PostApiRolesData = {
    body: RoleRequest;
    path?: never;
    query?: never;
    url: '/api/Roles';
};

export type PostApiRolesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostApiRolesResponses = {
    /**
     * OK
     */
    200: RoleResponse;
};

export type PostApiRolesResponse = PostApiRolesResponses[keyof PostApiRolesResponses];

export type GetApiRolesPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Roles/Permissions';
};

export type GetApiRolesPermissionsResponses = {
    /**
     * OK
     */
    200: Array<PermissionResponse>;
};

export type GetApiRolesPermissionsResponse = GetApiRolesPermissionsResponses[keyof GetApiRolesPermissionsResponses];

export type PostApiRolesAssignPermissionData = {
    body: AssignPermissionRequest;
    path?: never;
    query?: never;
    url: '/api/Roles/AssignPermission';
};

export type PostApiRolesAssignPermissionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostApiRolesAssignPermissionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiRolesAssignPermissionResponse = PostApiRolesAssignPermissionResponses[keyof PostApiRolesAssignPermissionResponses];

export type PostApiRolesRevokePermissionData = {
    body: RevokePermissionRequest;
    path?: never;
    query?: never;
    url: '/api/Roles/RevokePermission';
};

export type PostApiRolesRevokePermissionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostApiRolesRevokePermissionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiRolesRevokePermissionResponse = PostApiRolesRevokePermissionResponses[keyof PostApiRolesRevokePermissionResponses];

export type PostApiAuthLoginByTelegramData = {
    body: LoginByTelegramRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/LoginByTelegram';
};

export type PostApiAuthLoginByTelegramErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostApiAuthLoginByTelegramResponses = {
    /**
     * OK
     */
    200: AuthenticationResponse;
};

export type PostApiAuthLoginByTelegramResponse = PostApiAuthLoginByTelegramResponses[keyof PostApiAuthLoginByTelegramResponses];

export type PostApiAuthRefreshData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/Refresh';
};

export type PostApiAuthRefreshErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostApiAuthRefreshResponses = {
    /**
     * OK
     */
    200: AuthenticationResponse;
};

export type PostApiAuthRefreshResponse = PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];
